version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23121998
      POSTGRES_DB: hukidev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4

    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pqhuy2312@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 23121998
    restart: unless-stopped

volumes:
  postgres-data:
